Neptune Analytics Template - Update template type (#1426)
### Description

This is a PR to follow up on the error caused on the current build,
which `Mixed` is no longer one of the accepted type.

https://github.com/vercel/examples/actions/runs/22906043253/job/66464858165#step:7:51

```
Fetching template with slug "aws-neptune-analytics-nextjs-api-routes"...
Template validation failed:
[
  Error: Error in `aws-neptune-analytics-nextjs-api-routes` template -- "type" has an unknown item: "Mixed", it must be one of "Starter, Ecommerce, Blog, AI, Authentication, Edge Middleware, Edge Config, Portfolio, Virtual Event, SaaS, Documentation, CMS, Cron, Security, Realtime Apps, Monorepos, Web3, Admin Dashboard, Vercel Firewall, Backend, Multi-Tenant Apps, Microfrontends, Marketing Sites, CDN"
```