fix: version conflict of werkzeug
```
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
```

reference: https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls